### ISSUE TITLE
Needs an awesome icon

### ISSUE THREAD

**Issue by callumbwhyte** [callumbwhyte/super-value-converters#1]
Currently SuperValueConverters has no icon. Without an icon package repositories just show a placeholder, which is sad! 😞

The icon needs to be a square as it will be used on Our Umbraco and NuGet, and it needs to be easily identifiable. It doesn't need to be too complicated.

Perhaps a graphics wizard from the community could step up and make something awesome?

**Comment by leekelleher** [comment]
Hi @callumbwhyte, not sure if anyone else has sent a logo idea over yet.

I had a quick play with the old **"circle background with an icon from the [Noun Project](https://thenounproject.com/)"** idea. 😉 

Not sure if we're allowed to use new Umbraco brand colours? I couldn't decide which I preferred, so did both for contrast...

![supervalueconverters-logo-1](https://user-images.githubusercontent.com/209066/52631080-c1639d00-2eb5-11e9-83d8-51b7b38c8892.png)
![supervalueconverters-logo-2](https://user-images.githubusercontent.com/209066/52631081-c1639d00-2eb5-11e9-8833-1663938f47d2.png)

I've got the PSD if you want it?

If you use it, you'll need to credit the creator...
> [Energy by scarlett mckay from the Noun Project](https://thenounproject.com/scarlett.mckay/collection/misc/?i=1603715)

**Comment by callumbwhyte** [comment]
Hey @leekelleher, love your work! #h5yr

It's simple and exactly what the projected needed. If you could supply the PSD that would be great. I'll certainly give a credit to Scarlett McKay in the README.

Cheers,
Callum

**Comment by leekelleher** [comment]
Cool! I'll send a PR in the morning, with assets and README update.

**Comment by leekelleher** [comment]
PR submitted, #3 👍

**Comment by callumbwhyte** [comment]
I'll get this pushed out across all the different places, and bundled into NuGet with the next release soon!

Thanks for your work @leekelleher! #h5yr
