### ISSUE TITLE
Potential issue with Umbraco 7.15.1

### ISSUE THREAD

**Issue by richarth** [callumbwhyte/super-value-converters#10]
Hi,

I've just updated a site using v1.2 of the package to Umbraco 7.15.1 and the package seems to be causing the site to break.

When editing a page in the back office I get the error here https://gist.github.com/richarth/670ba0a06b41daf69ce846b397329a94

When accessing a page on the front end I get the following error https://gist.github.com/richarth/5f0079004cbd51902c965c50dced90a9

If I uninstall the package and then run the site then everything works as it should

Let me know if you need any further information

Richard

**Comment by callumbwhyte** [comment]
Hey @richarth,

Just checking if this is still an issue? I can't replicate it myself so it may be something specific to your setup.

Cheers,
Callum

**Comment by richarth** [comment]
Hi,

I'd removed the package due to the problems.  We have since updated the site to 7.15.3.

I've just tried installing the package again and it is still causing the site to error.  If I try to edit a page in the back office or view a page on the front end I get the following error:
https://gist.github.com/richarth/b5ad28a9f9b783ceb25a2b93d69ed501

If I try to regenerate the models then I get the following error:
https://gist.github.com/richarth/613e0e1850245e3ce7c7f927b3971184

When I uninstall the package the site starts working again.

I don't know if that helps.

Richard

**Comment by callumbwhyte** [comment]
Hey @richarth,

Sorry you're still having this issue.

It's definitely an issue in the package, but I can't pin down exactly what.

Are you able to confirm which models mode you are using?

Thanks,
Callum

**Comment by richarth** [comment]
No worries.  We're using the AppData models mode.

Richard

**Comment by callumbwhyte** [comment]
Hey @richarth,

Better late than never... I've patched this in the latest release - v1.3.0 available from all good package stores now!

Cheers,
Callum

**Comment by richarth** [comment]
Thanks Callum, I'll give it a try next week. Have a good weekend.

**Comment by richarth** [comment]
Hi Callum,

Sorry for the late response.  I've finally gotten around to testing this and I can confirm this is now fixed.  Thanks for the fix.

Richard

**Comment by callumbwhyte** [comment]
Thanks for confirming @richarth! Glad we got there eventually.
