### ISSUE TITLE
NestedContent items are not being converted to strongly typed models

### ISSUE THREAD

**Issue by robertjf** [callumbwhyte/super-value-converters#7]
When I generate my models, any Nested Content (and probably other types like StackedContent) with single Document Types configured should map to the appropriate type. Instead they are mapping to IEnumerable<IPublishedContent>.  See below for details:

DataType configuration:
![image](https://user-images.githubusercontent.com/818101/53664430-31df2c00-3cb4-11e9-85c1-8368708c658e.png)

Generated code:
```
		///<summary>
		/// Slideshow
		///</summary>
		[ImplementPropertyType("slides")]
		public IEnumerable<IPublishedContent> Slides
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("slides"); }
		}
```

What I expect:
```
		///<summary>
		/// Slideshow
		///</summary>
		[ImplementPropertyType("slides")]
		public IEnumerable<IPublishedContent> Slides
		{
			get { return this.GetPropertyValue<ProjectSlideshow>("slides"); }
		}

```

**Comment by robertjf** [comment]
actually, it seems this is only the case when the nested content is in single item mode - other properties based on Nested Content don't seem to be affected.

**Comment by callumbwhyte** [comment]
Thanks for raising this @robertjf - I also noticed this one and put a fix in.

If you download v1.0.1 of SuperValueConverters (available from all good package stores: Our Umbraco, NuGet, Github) it will fix your issue!
