### ISSUE TITLE
Errors after installing package

### ISSUE THREAD

**Issue by richarth** [callumbwhyte/super-value-converters#8]
Hi,

I've installed the package into an Umbraco 7.13.2 site to give it a go but I'm encountering errors.  You can see the error messages [here](https://gist.github.com/richarth/400201d0e27d381d13c263850802e67b).

The error in gistfile1.txt is the error I receive when I load the front end of the website.

The error in gistfile2.txt is the error I receive when I re-run the models builder generate models process.

If I uninstall the package then everything works OK again.

**Comment by callumbwhyte** [comment]
Hey @richarth! 👋

Firstly, thanks so much for giving SuperValueConverters a try! I'm sorry you ran into issues.

As the stack traces you've provided correctly show, there is a problem in v1.0.0 with configuring the package. I also came up against this issue and so I have put in a fix.

You can download v1.0.1 from NuGet, Our Umbraco or Github today and it will resolve your issue.

I'll close this issue for now, but feel free to open another in future if you need any help!

Cheers,
Callum
